import type { Metadata } from "next";
import "./globals.css";
import { getLingui } from "@/i18n/server";
import { LinguiProvider } from "@/i18n/client";
import { Locale } from "@/i18n/vars";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: Locale;
  };
};

export default function RootLayout({ children, params }: Props) {
  const { i18n } = getLingui();

  return (
    <html lang={params.locale}>
      <body>
        <LinguiProvider locale={i18n.locale as Locale} messages={i18n.messages}>
          {children}
        </LinguiProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ms" }];
}
